using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DigevoUsers.Models.Dto
{

    public class Custody {

        public int? idCustody { get; set; } = null;            // PK
        public int? idProduct { get; set; } = null;            // ID product, will be from DigevoProducts
        public decimal? id_cliente { get; set; } = null;         // Table 'cliente', from 3GMotion's Subscription Plataform
        public string value { get; set; } = null;               // Any value which will be 'reserved' for a future action
        public string code { get; set; } = null;               // Key generated by system, unique
        public string alias { get; set; } = null;               // Alias
        public bool? active { get; set; } = null;               // Flag for enabled or disabled
        public DateTime? expirationDate { get; set; } = null;  // Potential date for expiration
        public DateTime? creationDate { get; set; } = null;    // Creation date

    }

}